import fs from "node:fs";
import path from "node:path";
import { outputFolder, safeFilename, uniquePath } from "./documents";
import { assessBracket, findMaterial, thicknessFor, type Verdict } from "./loadCalc";
import { circle, extrude, isWatertight, toStl, translate, type Point, type Triangle } from "./mesh";

// The bracket itself.
//
// An L: a plate against the wall, an arm sticking out of it, and a triangular
// gusset in the corner because that is what stops the corner opening up. Screw
// holes through the wall plate, and a hole through the end of the arm if
// something is going to hang off it.
//
// Nothing here is generated by a model. A model chooses the numbers — how long,
// how thick, what it is made of — and this builds the shape from them, which is
// the only way to get a solid that is actually closed and actually printable.

export interface BracketSpec {
  /** How far the arm reaches from the wall, in millimetres. */
  reachMm: number;
  /** How tall the wall plate is, in millimetres. */
  heightMm: number;
  /** Across, in millimetres. */
  widthMm: number;
  /** How thick the plate and arm are, in millimetres. */
  thicknessMm: number;
  /** Screw hole diameter. 4.5 suits a common 4 mm screw. */
  screwDiameterMm: number;
  /** A hole through the end of the arm, for hanging something off. */
  hangingHoleMm?: number;
  /** The corner brace. Off is weaker and easier to print flat. */
  gusset: boolean;
}

export const DEFAULT_SPEC: Omit<BracketSpec, "reachMm" | "thicknessMm"> = {
  heightMm: 60,
  widthMm: 30,
  screwDiameterMm: 4.5,
  gusset: true,
};

/**
 * The wall plate: a rectangle standing in the XZ plane with two screw holes.
 *
 * Built flat and stood up afterwards, because everything in mesh.ts works on
 * flat outlines and turning it once is simpler than a second set of geometry.
 */
function wallPlate(spec: BracketSpec): Triangle[] {
  const { widthMm: w, heightMm: h, thicknessMm: t, screwDiameterMm: d } = spec;

  const outline: Point[] = [
    { x: 0, y: 0 },
    { x: w, y: 0 },
    { x: w, y: h },
    { x: 0, y: h },
  ];

  // Two screws up the middle, kept clear of the corner where the arm meets and
  // clear of the top edge.
  const inset = Math.max(d * 1.5, 8);
  const holes = [
    circle({ x: w / 2, y: h - inset }, d / 2),
    circle({ x: w / 2, y: inset + t * 1.5 }, d / 2),
  ];

  // Drawn in XY as width × height, extruded through the thickness, then laid so
  // that thickness runs along Y — the direction pointing away from the wall.
  const flat = extrude({ outline, holes }, t);
  return flat.map((triangle) => ({
    a: { x: triangle.a.x, y: triangle.a.z, z: triangle.a.y },
    // Swapping two axes mirrors it, so two corners are exchanged to wind it back.
    b: { x: triangle.c.x, y: triangle.c.z, z: triangle.c.y },
    c: { x: triangle.b.x, y: triangle.b.z, z: triangle.b.y },
  }));
}

/** The arm: a flat plate lying out from the wall, optionally with an end hole. */
function arm(spec: BracketSpec): Triangle[] {
  const { widthMm: w, reachMm: r, thicknessMm: t, hangingHoleMm } = spec;

  const outline: Point[] = [
    { x: 0, y: 0 },
    { x: w, y: 0 },
    { x: w, y: r },
    { x: 0, y: r },
  ];

  const holes: Point[][] = [];
  if (hangingHoleMm && hangingHoleMm > 0) {
    const from = Math.max(hangingHoleMm, 8);
    if (r - from > hangingHoleMm) {
      holes.push(circle({ x: w / 2, y: r - from }, hangingHoleMm / 2));
    }
  }

  return extrude({ outline, holes }, t);
}

/** The gusset: a right triangle in the corner, which is what carries the moment. */
function gusset(spec: BracketSpec): Triangle[] {
  const { widthMm: w, reachMm: r, heightMm: h, thicknessMm: t } = spec;

  // Two thirds of each, so it braces the corner without becoming the whole part.
  const out = Math.min(r - t, (r - t) * 0.7);
  const up = Math.min(h - t, (h - t) * 0.7);
  if (out <= 1 || up <= 1) return [];

  // Drawn in the side plane (Y out from the wall, Z up), then extruded across
  // the width and turned so the extrusion runs along X.
  const outline: Point[] = [
    { x: 0, y: 0 },
    { x: out, y: 0 },
    { x: 0, y: up },
  ];

  const thick = Math.min(w, Math.max(t, w * 0.4));
  const flat = extrude({ outline }, thick);
  return flat.map((triangle) => ({
    a: { x: triangle.a.z, y: triangle.a.x, z: triangle.a.y },
    b: { x: triangle.c.z, y: triangle.c.x, z: triangle.c.y },
    c: { x: triangle.b.z, y: triangle.b.x, z: triangle.b.y },
  }));
}

/**
 * The whole thing.
 *
 * The three parts are built where each is easiest and moved into place. They
 * overlap deliberately at the corner: a slicer unions overlapping solids, and
 * an overlap is far more reliable than trying to make three surfaces meet
 * exactly along a shared edge.
 */
export function buildBracket(spec: BracketSpec): Triangle[] {
  const { thicknessMm: t, widthMm: w } = spec;

  const parts: Triangle[] = [
    // The plate sits against the wall at y = 0.
    ...wallPlate(spec),
    // The arm runs out from it, sitting on top of the plate's foot.
    ...translate(arm(spec), { z: 0 }),
  ];

  if (spec.gusset) {
    const brace = gusset(spec);
    // Centred across the width, starting just past the plate's thickness.
    parts.push(...translate(brace, { x: (w - Math.min(w, Math.max(t, w * 0.4))) / 2, y: t, z: t }));
  }

  return parts;
}

export interface DesignedBracket {
  path: string;
  filename: string;
  folder: string;
  spec: BracketSpec;
  verdict: Verdict;
  triangles: number;
  watertight: boolean;
}

export interface DesignRequest {
  /** What it is holding up, for the file name. */
  itemName: string;
  massKg: number;
  reachMm: number;
  material?: string;
  widthMm?: number;
  /** Left out, the thickness needed for a safety factor of 3 is worked out. */
  thicknessMm?: number;
  heightMm?: number;
  infillPercent?: number;
  hangingHoleMm?: number;
  gusset?: boolean;
}

/**
 * Work out the bracket, check it, build it, write it.
 *
 * The order matters: the sums come first and the geometry is built from what
 * they said, so the file on disk and the answer he is given are the same
 * bracket. A thickness he did not specify is solved for rather than guessed.
 */
export function designBracket(request: DesignRequest): DesignedBracket {
  const material = findMaterial(request.material ?? "petg");
  if (!material) {
    throw new Error(
      `I don't have figures for "${request.material}", sir. I know PLA, PETG, ABS, ASA, nylon, aluminium, steel, plywood and pine.`
    );
  }
  if (!(request.massKg > 0)) throw new Error("How heavy is it, sir? I can't work it out without that.");
  if (!(request.reachMm > 0)) throw new Error("How far out from the wall does it need to reach, sir?");

  const widthMm = request.widthMm ?? Math.max(25, Math.min(60, request.reachMm * 0.6));
  const infillPercent = request.infillPercent ?? 40;

  const thicknessMm =
    request.thicknessMm ??
    Math.max(
      4,
      thicknessFor(
        { massKg: request.massKg, reachMm: request.reachMm, widthMm, material, infillPercent },
        3
      )
    );

  const spec: BracketSpec = {
    ...DEFAULT_SPEC,
    reachMm: request.reachMm,
    widthMm,
    thicknessMm,
    heightMm: request.heightMm ?? Math.max(40, request.reachMm * 1.2),
    hangingHoleMm: request.hangingHoleMm,
    gusset: request.gusset ?? true,
  };

  const verdict = assessBracket({
    massKg: request.massKg,
    reachMm: spec.reachMm,
    widthMm: spec.widthMm,
    thicknessMm: spec.thicknessMm,
    material,
    infillPercent,
    screwSpacingMm: spec.heightMm - Math.max(spec.screwDiameterMm * 1.5, 8) * 2,
    screws: 2,
  });

  const triangles = buildBracket(spec);
  const { closed } = isWatertight(triangles);

  const folder = path.join(outputFolder(), "Models");
  fs.mkdirSync(folder, { recursive: true });
  const target = uniquePath(
    folder,
    safeFilename(`${request.itemName} bracket`.slice(0, 60), "stl")
  );
  fs.writeFileSync(target, toStl(triangles, `Axis bracket for ${request.itemName}`));

  return {
    path: target,
    filename: path.basename(target),
    folder,
    spec,
    verdict,
    triangles: triangles.length,
    watertight: closed,
  };
}
